spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5434/wallet'
    password: 'wallet'
    username: 'wallet'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQL95Dialect'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true